name: CREATE_RELEASE_TMP

on:
  workflow_dispatch:

jobs:
  create:
    name: Create missing v0.0.11 release
    runs-on: ubuntu-latest
    steps:
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          tag: v0.0.11
          name: Release v0.0.11
          generateReleaseNotes: true
          allowUpdates: true
